-- drop schema marketplace cascade;

CREATE SCHEMA marketplace;

CREATE TABLE marketplace.usuario (
    id SERIAL,
    nome VARCHAR(255),
    login VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nasc DATE,

    CONSTRAINT pk_usuario PRIMARY KEY(id),
    CONSTRAINT uk_usuario_login UNIQUE(login)
);

-- novo tipo 'genero' para os generos dos filmes/series
CREATE TYPE marketplace.GENERO AS ENUM (
	'Action', 'Adventure', 'Animation', 'Biography', 
	'Comedy', 'Crime', 'Documentary', 'Drama', 
	'Family', 'Fantasy', 'Film-Noir', 'History', 
	'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 
	'Sci-Fi', 'Short', 'Sport', 'Thriller', 'War', 'Western');

-- novo tipo 'idioma' para os idiomas dos filmes/series
CREATE TYPE marketplace.IDIOMA AS ENUM (
	'Arabic', 'Cantonese', 'Central Khmer', 
	'Chinese', 'Cornish', 'Dutch', 'English', 
	'French', 'Gaelic', 'German', 'Greek', 
	'Hebrew', 'Hungarian', 'Italian', 'Japanese', 
	'Korean', 'Mandarin', 'Polish', 'Portuguese', 
	'Romanian', 'Russian', 'Spanish', 'Swedish', 'Thai', 
	'Ukrainian', 'Vietnamese', 'Xhosa', 'Zulu');

CREATE TABLE marketplace.midia (
    id SERIAL,
    titulo VARCHAR(255) NOT NULL,
    sinopse TEXT,
	idiomas marketplace.IDIOMA[],
	generos marketplace.GENERO[],
    avaliacao DECIMAL(3, 2),
    poster VARCHAR(255),
    atores VARCHAR(255),
    dt_lancamento DATE,
    valor DECIMAL(10, 2),

    CONSTRAINT pk_midia PRIMARY KEY(id)
);

CREATE TABLE marketplace.filme (
    -- id INT GENERATED BY DEFAULT AS IDENTITY,
    duracao INT -- Duração em minutos inteiros.

  --   CONSTRAINT pk_filme PRIMARY KEY(id),
  --   CONSTRAINT fk_filme_eh_midia FOREIGN KEY(id) 
		-- REFERENCES marketplace.midia(id) ON DELETE CASCADE
) INHERITS(marketplace.midia);

CREATE TABLE marketplace.serie (
    -- id INT GENERATED BY DEFAULT AS IDENTITY,
    temporadas INT
    
  --   CONSTRAINT pk_serie PRIMARY KEY(id),
  --   CONSTRAINT fk_serie_eh_midia FOREIGN KEY(id) 
		-- REFERENCES marketplace.midia(id) ON DELETE CASCADE
) INHERITS(marketplace.midia);

CREATE TABLE marketplace.alugou (
    usuario_id INT,
    midia_id INT,
    dt_inicio DATE NOT NULL,
    dt_expira DATE NOT NULL,
    
    CONSTRAINT pk_alugou PRIMARY KEY (usuario_id, midia_id),
    CONSTRAINT pk_usuario_alugou FOREIGN KEY (usuario_id) 
		REFERENCES marketplace.usuario(id),
    CONSTRAINT pk_midia_foi_alugada FOREIGN KEY (midia_id) 
		REFERENCES marketplace.midia(id),
    CONSTRAINT ck_dt_aluguel CHECK(dt_inicio < dt_expira)
);

CREATE TABLE marketplace.comprou (
    usuario_id INT,
    midia_id INT,
    dt_compra DATE NOT NULL,

    CONSTRAINT pk_comprou PRIMARY KEY (usuario_id, midia_id),
    CONSTRAINT fk_usuario_comprou FOREIGN KEY (usuario_id) 
		REFERENCES marketplace.usuario(id),
    CONSTRAINT fk_midia_foi_comprada FOREIGN KEY (midia_id) 
		REFERENCES marketplace.midia(id)
);

CREATE TABLE marketplace.SPRING_SESSION (
  PRIMARY_ID CHAR(36) NOT NULL,
  SESSION_ID CHAR(36) NOT NULL,
  CREATION_TIME BIGINT NOT NULL,
  LAST_ACCESS_TIME BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INT NOT NULL,
  EXPIRY_TIME BIGINT NOT NULL,
  PRINCIPAL_NAME VARCHAR(100),
  CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON marketplace.SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON marketplace.SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON marketplace.SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE marketplace.SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES BYTEA NOT NULL,
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) 
  	REFERENCES marketplace.SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
